### ISSUE TITLE
Wrong power supply currents

### ISSUE THREAD

**Issue by ghost** [lnls-fac/va#52]
After starting the VA by sirius-vaca.py:

```
$ caget VA-SIPS-QFA-FAM
VA-SIPS-QFA-FAM                0

$ caget VA-SIPS-SFA-FAM
VA-SIPS-SFA-FAM                0
```

**Comment by ghost** [comment]
Fixed by removing call to shift_record_names inside _init_magnets_and_power_supplies in accelerator_model.py.

**Comment by ghost** [comment]
There is something strange with the orbit. It is nonzero when VA is started.

**Comment by xresende** [comment]
I tested it here, @afonsoharuo. For SI I get 0 um when there is no current and <1um when there is current. The value different from 0 is because now it is calculating 6D closed orbit. Do you have a different behaviour?

**Comment by ghost** [comment]
The values I get are small; I didn't realise it was because of the 6D tracking. @LuanaVilela fixed the issue with the power supplies.
